### ISSUE TITLE
Missing SIU message types (everything except SIU_S12)

### ISSUE THREAD

**Issue by alexyuisingwu** [crs4/hl7apy#103]
The only SIU message supported seems to be SIU_S12. 

If you try creating any other SIU message (S13, S14, S15, S16, S17, S27, etc.), you get an error:

`test = Message('SIU_S13')`

`hl7apy.exceptions.InvalidName: Invalid name for Message: SIU_S13`

It looks like other options are just not included in messages.py

**Comment by svituz** [comment]
Sorry, for not responding. I fixed this in develop branch. It will be included in the next release

**Comment by svituz** [comment]
Inclded in release 1.3.5
