### ISSUE TITLE
2.6 segments bug

### ISSUE THREAD

**Issue by cschwerdtner** [crs4/hl7apy#114]
with v2.6 I use this assignment:
```
hl7Version = "2.6"
m = Message("ADT_A01", version=hl7Version, validation_level=VALIDATION_LEVEL.TOLERANT)
m.in1.in1_49 = pat.PA_VERSNR
```

But the value is written into **Field 46 and not 49**.
I checked it and found that in v2.6 the segments.py is missing some lines:

```
('IN1_36', FIELDS['IN1_36'], (0, 1), 'FIE'),
('IN1_37', FIELDS['IN1_37'], (0, 1), 'FIE'),
('IN1_39', FIELDS['IN1_39'], (0, 1), 'FIE'),
('IN1_42', FIELDS['IN1_42'], (0, 1), 'FIE'),
('IN1_43', FIELDS['IN1_43'], (0, 1), 'FIE'),
('IN1_44', FIELDS['IN1_44'], (0, -1), 'FIE'),
```
3 lines are missing, so field 49 is written to field 46 when using `hl7_message = m.to_mllp()`

**Comment by svituz** [comment]
Hi thanks, you're right. I fixed this in develop branch. I'll work on a release and it will be included
