### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by ancheypeng** [crs4/hl7apy#115]
Is there any known issues with this package on Python 3.8? If not, is there a reason why 3.8 is not listed as a supported version?

The [pypi page](https://pypi.org/project/hl7apy/) for the project lists Python 3.8 and 3.9 as classifiers.

**Comment by yankov-sdx** [comment]
Are you referring to the README.md not listing 3.8? I am using hl7apy on Python 3.12 successfully, but ymmv.

For the latest code on github, it looks like tests are running/passing for Pythons from 3.7 to 3.12.

**Comment by ancheypeng** [comment]
Yeah mainly just wondering why it specifically lists up to 3.7 on the README, but in other places (pypi and the tests) higher versions are listed as well.

**Comment by svituz** [comment]
Hi @ancheypeng,
we just need to update the README. We don't have any known problems with Python 3.8 or higher
