### ISSUE TITLE
v2_8_2/fields.py and segments.py OBR_14, OBR_15, OBR_27, PID_28 withdrawn (WD) fields missing

### ISSUE THREAD

**Issue by cristynkells** [crs4/hl7apy#117]
OBR_14, OBR_15, OBR_27, PID_28 withdrawn fields are missing from v2_8_2/fields.py and segments.py, and as a result all the HL7 segment fields are shifted and parsing the HL7 fails. Withdrawn fields should not be omitted from fields.py and segments.py, they should be flagged with an 'WD'. Can this be fixed?

**Comment by svituz** [comment]
Thanks for issuing this. We'll work on it
