### ISSUE TITLE
Is it possible to create a validation object instead of writting to file?

### ISSUE THREAD

**Issue by joofio** [crs4/hl7apy#127]
As far as I am aware, there is no way to validate and get the result into an object. could we add that feature?

**Comment by jgarciaroca** [comment]
A PR exist for that: https://github.com/crs4/hl7apy/pull/121

if you pass the validator a StringIO or BytesIO object, it will write there. Or as an option use the return_errors=True and you will have a namedtuple as return object including the warnings and the errors.

**Comment by joofio** [comment]
added a plus one. thanks for that! Hope it can be merged soon.

**Comment by jgarciaroca** [comment]
PR was merged 24th of July

**Comment by svituz** [comment]
Closing sing it is merged
