### ISSUE TITLE
`SCH.9` should be a numeric field

### ISSUE THREAD

**Issue by hatahet** [crs4/hl7apy#135]
As per the [spec](https://hl7-definition.caristix.com/v2/HL7v2.8/Fields/SCH.9), `SCH.9` is a `NM` field. However, it is defined as a `WD` field in the code.

**Comment by germiBest** [comment]
@hatahet according to documentation, this field was retained for backward compatibility only and withdrawn and removed as of v2.7.
Withdrawn fields are marked as WD in the project, check the end of this section:
https://github.com/crs4/hl7apy/blob/develop/docs/tutorial/index.rst#datatypes
