### ISSUE TITLE
Proper parsing of fields of datatype TX

### ISSUE THREAD

**Issue by rkjaran** [crs4/hl7apy#15]
According to the standard, the repetition seperator ('~') is used to represent a line break in the TX data type.

Currently this is what happens:
```
>>> field = Field('OBX_5', datatype='TX')
>>> field.value = 'a~b~c'
>>> field.to_er7()
'a\\R\\b\\R\\c'
>>> parse_field('a~b~c', name='TX').to_er7()
'a\\R\\b\\R\\c'
```
where the returned ER7 should be 'a~b~c', i.e. the repetition seperator shouldn't be escaped.

**Comment by svituz** [comment]
Actually this is the way it is supposed to work. 
A ``Field`` object represents only one occurrence of an HL7 field, so when you assign a string to the field, hl7apy considers it as the value of that occurrence and escapes the special characters (infact \\R\\ is the HL7 escaping of ~). 
The correct way to achieve your goal is to create three different Fields of the same type and add them to the ``Segment`` children, as in the following example:
```python
>>> f1 = Field('OBX_5', datatype='TX')
>>> f1.value = 'a'
>>> f2 = Field('OBX_5', datatype='TX')
>>> f2.value = 'b'
>>> f3 = Field('OBX_5', datatype='TX')
>>> f3.value = 'c'
>>> s = Segment('OBX')
>>> s.add(f1)
>>> s.add(f2)
>>> s.add(f3)
>>> s.to_er7()
'OBX|||||a~b~c'
```

**Comment by rkjaran** [comment]
No, I think you understood me correctly in your first answer and your solution is probably what I was looking for.

I am creating OBX segments with free-flow text in OBX.5, and instead of adding each line as a repetition of a Field I was just replacing '\n' by '~' and setting that as the value of OBX.5.

From HL72.3.1 2.8.45:
> Since TX data is intended for display purposes, the repeat
> delimiter, when used with a TX data field, implies a series of
> repeating lines to be displayed on a printer or
> terminal. Therefore, the repeat delimiters are regarded as
> paragraph terminators or hard carriage returns (e.g., they would
> display as though a CR/LF were inserted in the text (DOS type
> system) or as though a LF were inserted into the text (UNIX style
> system)).

**Comment by svituz** [comment]
Ok, I close the issue then.

Vittorio
