### ISSUE TITLE
A28 and A04 Support in Version 2.4

### ISSUE THREAD

**Issue by dixonwh** [crs4/hl7apy#16]
Hello,

I am working on an integration project where the systems are utilizing HL7 v2.4 for Patient Administration transactions and messaging. Specifically the A04 and A28 events. It appears that these events are not supported in hl7apy, since hl7apy.v2_4.messages doesn't contain a configuration for ADT_A04 or ADT_A28. Is this correct? If so, I would be happy to work on a pull request to add the configuration, if that would be useful.

Thanks,
Dixon

**Comment by svituz** [comment]
Hello Dixon,
I checked version 2.4 specification and I couldn't find the message types you're using. I mean, there are A04 and A28 event type but the correct messages are respectively ADT_A01 and ADT_A05 (check that out yourself to be sure), while ADT_A04 and ADT_A28 doesn't exist, neither in further HL7 versions.
To use the messages and event types you need, you just need to set the correct value to the MSH.2.2 component. 
For example:
```python
a04_msg = Message("ADT_A01", version="2.4")
a04_msg.msh.msh_9.msg_1 = "ADT"
a04_msg.msh.msh_9.msg_2 = "A04"

a28_msg = Message("ADT_A05", version="2.4")
a28_msg.msh.msh_9.msg_1 = "ADT"
a28_msg.msh.msh_9.msg_2 = "A28"
```
Regards,
Vittorio

**Comment by dixonwh** [comment]
Vittorio,

Thank you very much for the response and the code samples. I didn't review the specs closely enough to see the message type differences between 2.3 (version we were using previously) and 2.4. This was a great help!

Thanks,
Dixon
