### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by mhdmatt** [crs4/hl7apy#21]
Love this and its server as well. But when can we make it python 3?

**Comment by svituz** [comment]
Hi mhdmatt,
sorry for the late answer. Python 3 support surely is one of the feature we want to develop, but unfortunately I can't give you an answer about when we're doing it.

**Comment by JonathonReinhart** [comment]
I think this issue can be closed since #23 was merged.

**Comment by svituz** [comment]
It really can, thank you
