### ISSUE TITLE
No module named 'cPickle' while installing from pip3

### ISSUE THREAD

**Issue by rastersoft** [crs4/hl7apy#27]
I'm trying to install hl7apy using pip3, but I receive this error:

Collecting hl7apy
  Downloading hl7apy-1.1.2.tar.gz (642kB)
    100% |████████████████████████████████| 645kB 15.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5ggypsax/hl7apy/setup.py", line 27, in <module>
        import hl7apy
      File "/tmp/pip-build-5ggypsax/hl7apy/hl7apy/__init__.py", line 26, in <module>
        import cPickle
    ImportError: No module named 'cPickle'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5ggypsax/hl7apy/

**Comment by rastersoft** [comment]
Ok, I suspect the problem is that it's trying to install version 1.1.2...

**Comment by rastersoft** [comment]
Ok, it seems that the changes to support python3 still haven't been published as stable...

**Comment by svituz** [comment]
Hello @rastersoft. We've just released the 1.2.0 which can be installed using pip and pip3.
