### ISSUE TITLE
not able to run example server , client

### ISSUE THREAD

**Issue by sayan801** [crs4/hl7apy#30]
i have downloaded latest version from github 1.2.0.. and trying to run example.. i have tried on both ubuntu 14.04 and 16.04.. i get following error..

````
ubuntu@ip-121.23.23.23:~/github-code/hl7apy/examples/lab62$ python server.py 
  File "server.py", line 28
    from SocketServer as StreamRequestHandler, TCPServer
                       ^
SyntaxError: invalid syntax
ubuntu@ip-121.23.23.23:~/github-code/hl7apy/examples/lab62$ 
````

Is there any dependency needs to be installed ?

**Comment by svituz** [comment]
Hi @sayan801,
no you don't need any dependency. As it says, there is a syntax error. It should be 

`from SocketServer import StreamRequesthandler, TCPServer`

That said, please be aware that the examples are outdated, and we need to update them to use new MLLP server implementation.

Vittorio
