### ISSUE TITLE
Hl7 v2.7 support

### ISSUE THREAD

**Issue by tomchiverton** [crs4/hl7apy#32]
HL7 v2.7 messages have an extra character in the MSH field:

MSH|^~\&a|...

this causes InvalidEncodingChars exception during _split_msh in the parser.

**Comment by tomchiverton** [comment]
See 1.1 on http://www.ringholm.com/docs/00750_en_HL7_27_features.htm

**Comment by svituz** [comment]
Hello,
as I commented in the PR, we've just released version 1.3.0 that support version 2.7.
