### ISSUE TITLE
Isn't the handler reply method return message send automatically to the mllp Client ?

### ISSUE THREAD

**Issue by merylb** [crs4/hl7apy#36]

**Comment by merylb** [comment]
Hello,
I need to know if i have to create a tcp object that send the reply message of there is another way to do that directly from MllpServer

**Comment by merylb** [comment]
thank you for your reply, but how can i send an hl7 message directly from MLLPServer i won't to create every time a new client so as to send the response like i done here:

![image](https://user-images.githubusercontent.com/33625598/46355004-d141b980-c657-11e8-8220-0956d95b9a3d.png)



how can i access the mllpServer principale socket

**Comment by svituz** [comment]
I don't understand your needs. From your code, it seems that when you receive a message, you create a response (`msg = hl7_msg()`)  and sends it again to your own server. If what you want is just sending `msg` as ack to the original client, your doing it wrong: you just have to return it using `return msg.to_mllp()`.
That said, to answer your question, the MLLP Server is implemented to create a new instance of the correct Handler everytime it receives a new message, so if you want to change this behavior you should extend or reimplement, the MLLPServer. If you want to check the current implementation you can find it  [here](https://github.com/crs4/hl7apy/blob/develop/hl7apy/mllp.py)

**Comment by svituz** [comment]
Sorry, I closed it unintentionally

**Comment by merylb** [comment]
No i dont send the reply to the same MllpServer as you can see the port number of the server and the client is different am runing two programs in defferent ports i' hadn't put the other program Screenshot here is the full details:

program1:

![image](https://user-images.githubusercontent.com/33625598/46359448-3948cd80-c661-11e8-9f8a-2d9b227aae65.png)



program2:

![image](https://user-images.githubusercontent.com/33625598/46359542-6301f480-c661-11e8-957d-200e82ab29b3.png)

i montion that hl7_msg() is a function that return a hl7 encoded message

my purpose is to not use a mllpClient to send the first message and have somthing like 

server.socket.send(hl7_msg())

**Comment by merylb** [comment]
thank you
