### ISSUE TITLE
Getting the value from subcomponent doesn't seem to work

### ISSUE THREAD

**Issue by rstoermer** [crs4/hl7apy#60]
I got the following PV1: 

`PV1|1|I|16&Station 16&20051121231500&^1601&Zimmer 1601&20051121231500&^1601 2&Zimmer 1601, Bett2&20051121231500&^NCH&Neurochirurgie&20051121231500&^|||||||||||||0|||173887^^^&PROSIGHT&L^&PROSIGHT&L^&PROSIGHT&L^20051121231500&YYYYMMDDHHMMSS^|||||^stat|20051121231500^YYYYMMDDHHMMSS||||||||||||||||N|||20051121231500^YYYYMMDDHHMMSS||||||553093^^&PROSIGHT&L^&PROSIGHT&L^^20051121231500&YYYYMMDDHHMMSS^^76196^86446^72644||
`

When iterating through the parsed fields and printing the name and value, I get:

> <Field PV1_3 (ASSIGNED_PATIENT_LOCATION) of type PL>
    <Component PL_1 (POINT_OF_CARE) of type None> - 16&Station 16&20051121231500&
    <Component PL_2 (ROOM) of type None> - 1601&Zimmer 1601&20051121231500&
    <Component PL_3 (BED) of type None> - 1601 2&Zimmer 1601, Bett2&20051121231500&
    <Component PL_4 (FACILITY_HD) of type HD> - NCH&Neurochirurgie&20051121231500

Now I want to access the values in the subcomponent, e.g. Station 16. If I do:
`    for component in pv1.pv1_3.children:
        print(component.value)`

I get

> 16&Station 16&20051121231500&
> 1601&Zimmer 1601&20051121231500&
> 1601 2&Zimmer 1601, Bett2&20051121231500&
> NCH&Neurochirurgie&20051121231500

which is not what I want. When getting the children of pv1.pv1_3.pl_1 I get:

`[<SubComponent IS>, <SubComponent IS>, <SubComponent IS>, <SubComponent IS>]
`

v1.pv1_3.pl_1.children[0].value however only returns <hl7apy.base_datatypes.IS object at 0x106977640>

Is this intentionally? How can I access the single value?

**Comment by svituz** [comment]
Hi,
you can get the value of the subcomponent using pv1.pv1_3.pl_1.children[0].value.value or 
1.pv1_3.pl_1.children[0].to_er7()

I admit it is unintuitive and a kind of incoherent with the other cases. We'll see if we'll change this behaviour in the future
