### ISSUE TITLE
Time zone offset doesn't support UTC+14

### ISSUE THREAD

**Issue by tkthanikai** [crs4/hl7apy#74]
Hi,

In base_datatypes.py, in class TM(DateTimeDataType), the offset allows a max hh value of 12. While I understand it is hour, if valid UTC offset values like UTC+14 (New Zealand, Alaska) had to be set, the current code doesn't support it and throws an error. 
<img width="682" alt="Screen Shot 2020-04-08 at 12 13 58 PM" src="https://user-images.githubusercontent.com/29109715/78824921-012bf480-7994-11ea-9ddc-217e2189b0f1.png">

I guess valid UTC offset can be supported in future?

Thanks

**Comment by svituz** [comment]
You're right. I should have fixed it in develop branch. We will include the fix in the next release.

Thanks
