### ISSUE TITLE
External links going to fraudulent websites

### ISSUE THREAD

**Issue by lukeconner** [crs4/hl7apy#77]
I'm not sure if this is the best place to leave this, but you link to a blog post with helpful links/examples.  On his blog post he links to your documentation page.  Except your documentation page has now changed, and his link goes to a page telling you your antivirus software has expired and you need to renew it.

**Comment by svituz** [comment]
Hi @lukeconner, 
I noticed that you informed Michael in his blog and he fixed it. 
Thank you.
