### ISSUE TITLE
Improve Documentation on How to Use Fields

### ISSUE THREAD

**Issue by cancan101** [crs4/hl7apy#8]
For example how are the constants in: https://github.com/crs4/hl7apy/blob/781dea7c5eb37256b7a4151b39ff3e45910cf39a/hl7apy/v2_2/fields.py#L22 used?

**Comment by rashmitpankhania** [comment]
can you explain how to add multiple obx in message in ORU_R01 with group name ORU_R01_PATIENT_RESULT
