### ISSUE TITLE
outbound functionality

### ISSUE THREAD

**Issue by baileyglen** [crs4/hl7apy#80]
Am I correct in thinking that there is currently no outbound server functionality?

My use case:
Incoming Server
- Receive order message (ORU)
- Respond with ACK 
- Initiate Processing (5-7 days)
Outgoing Server
- Send Observation Result (OBR)
- Receive ACK

**Comment by svituz** [comment]
Hi @baileyglen, 
the client is not implemented in the package. You can find an example of a client in the `examples` directory
