### ISSUE TITLE
How to add custom Segment structure in order to parse them easily

### ISSUE THREAD

**Issue by codeKonami** [crs4/hl7apy#88]
Hello,

Is there a way to add some custom Segments and Fields to be able to parse them afterwards ?

Something like :

```py


hl7apy.add_segment(
'ZBE': ('sequence',
            (('ZBE_1', FIELDS['ZBE_1'], (0, 1), 'FIE'),
             ('ZBE_2', FIELDS['ZBE_2'], (0, 1), 'FIE'),
             ('ZBE_3', FIELDS['ZBE_3'], (0, 1), 'FIE'),
))
```

**Comment by svituz** [comment]
Hi, @codeKonami. Z-segments are supported without the need to specify the structure. [Here](http://crs4.github.io/hl7apy/tutorial/index.html#z-elements) you can see how they work, what is allowed and what is not. If you want to specify the structure of the segment, use [message profiles](http://crs4.github.io/hl7apy/tutorial/index.html#message-profiles)

**Comment by codeKonami** [comment]
Thanks @svituz!
